# Auto Updates if version is not equal to plugin hardcoded value
version: 32

# Custom Server Mod
# If plugin has detected the Mod wrongly,
# or you are using Unknown Server Mod, you can manually set the Mod.
# Leave it blank when you are already using popular Branches, otherwise write a most suitable one
# Spigot / PaperSeries (include Paper/Purpur/...) / Folia
server-mod: ''

# Language file
# it loads language/EXAMPLE.yml
plugin-language: default

check-update: true

# Force Replacing old configs to the latest configs (base on config version)
# true: Replace all existing configs with default value (with comments)
# false: adding new keys to the current one (without comments)
update-replace-config: false

# What identifier should Doll spawn with
# Must be 0 or 1 letter
# Should avoid common character (username available / being used by other plugins)
# Some characters will cause confusion to Vanilla Command System
doll-identifier: '-'

# Any Doll name that shouldn't be used
preserved-doll-name:
    - ''

# Should Server adjust player count to ensure the capacity of real player does not change
adjustable-max-player: true

# How many doll can spawn in the server
# -1 : unlimited, 0 : disable spawning
server-max-doll-spawn: -1

broadcast-doll-death: true
broadcast-doll-join: false
broadcast-doll-disconnect: false

# Will doll info being displayed on Ping status
# This affects the display of online counts and max player counts
display-doll-when-ping: false

# Will doll with hidden flag can be seen by OP
# Include Tab list and player model in world
# If hidden, no physical interaction can be done to Doll by Player
op-can-see-hidden-doll: true

# Add permission to all Dolls
# It could be helpful in some circumstances
doll-permission:
  - ''

# Add metadata to Doll when Spawn
# i.e. Residence will recognize "NPC" and let player bypass
doll-metadata:
  - ''

# Delay between each message (in tick)
# Avoid Spamming message too fast
chat-when-join-interval: 10

# What to say by Doll when Joined
# Each element represents a message
# Use "/" to indicate command
# Execution order : from top to bottom
# Variables : %name% -> Player Name; %uuid% -> Player UUID
chat-when-join:
  - ''

# Manipulate player when Joining Server
# To support some doll actions
# Converted Player will be kicked automatically if server Reload / Shutdown
convert-player: false

# Broadcast kick reason for converted player
# Call when server is reload or shutdown
broadcast-convert-shutdown: true

# Should Doll connections use specified Proxy-IP and Proxy-Port
# Instead of default 127.0.0.1:25565
# If BungeeCord has enabled, this option will be ignored
force-proxy-ip: false

# Proxy IP (BungeeCord / Other)
# Doll will connect to this when proxy-type is not empty
# see proxy server config
proxy-ip: 127.0.0.1

# Proxy Port (BungeeCord)
# for joining server
# see proxy server config
proxy-port: 25565

# Auto Join Delay
# The delay between each Joining of Doll
# Adjust by real performance
# in second
auto-join-delay: 1